sudo: true


language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



global: GRADLE_OPTS="-Xmx2048m"
before_install: chmod +x gradlew
before_script: chmod +x gradlew
script:
   ./gradlew GdxSqlite:build --stacktrace
