/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_longri_gdx_sqlite_SQLiteBuild */

#ifndef _Included_de_longri_gdx_sqlite_SQLiteBuild
#define _Included_de_longri_gdx_sqlite_SQLiteBuild
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_longri_gdx_sqlite_SQLiteBuild
 * Method:    add
 * Signature: ([FIIF)V
 */
JNIEXPORT void JNICALL Java_de_longri_gdx_sqlite_SQLiteBuild_add
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
